type User {
	id: ID
	name: String
	email: String
	emailVerified: DateTime
	image: String
	createdAt: DateTime
	updatedAt: DateTime
	sessions: [Session]
	apps: [App]
}

type App {
  id: ID
  taxonomies: [taxonomies]
  description: String
  title: String
  url: String
}

type Settings {
	id: ID
	title: String
}

type Query {
	allUsers: [User!]!
	user(id: ID!): User!
	settings: Settings!
}
